# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-07 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EditImgList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='images2', verbose_name='编辑区图片存放')),
            ],
            options={
                'verbose_name': '编辑区图片列表',
                'verbose_name_plural': '编辑区图片列表',
            },
        ),
        migrations.CreateModel(
            name='ImageList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='images1', verbose_name='图片上传路径')),
            ],
            options={
                'verbose_name': '图片列表',
                'verbose_name_plural': '图片列表',
            },
        ),
        migrations.AddField(
            model_name='editimglist',
            name='img_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cluster.ImageList'),
        ),
    ]
