# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-26 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.CharField(max_length=20, verbose_name='x轴坐标')),
                ('y', models.CharField(max_length=20, verbose_name='y轴坐标')),
                ('w', models.CharField(max_length=20, verbose_name='图片宽度')),
                ('h', models.CharField(max_length=20, verbose_name='图片高度')),
                ('img', models.CharField(max_length=64, verbose_name='所标图片')),
            ],
            options={
                'verbose_name': '坐标管理',
                'verbose_name_plural': '坐标管理',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.FileField(upload_to='images', verbose_name='图片上传路径')),
            ],
            options={
                'verbose_name': '图片',
                'verbose_name_plural': '图片',
            },
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_attr', models.CharField(max_length=64, verbose_name='人脸属性')),
                ('body_attr', models.CharField(max_length=64, verbose_name='人体属性')),
            ],
            options={
                'verbose_name': '任务类型',
                'verbose_name_plural': '任务类型',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
            ],
            options={
                'verbose_name': '用户管理',
                'verbose_name_plural': '用户管理',
            },
        ),
    ]
